In [6]:
import pandas as pd

from google.colab import files

uploaded = files.upload()

Saving assignment1Sort.csv to assignment1Sort (3).csv

In [8]:
for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

User uploaded file "assignment1Sort.csv" with length 5257 bytes

In [9]:
print(uploaded)

{'assignment1Sort.csv': b'First Name,Middle Initial,Last Name,Address,Major,Completed Credit Hours,Scholarship Received,GPA\r\nPat,Corbin,Mcmahon,Unt DP,MBA,15,TRUE,3.70 \r\nTruman,Mikaela,Holquin,Unt Main Campus,MS,18,FALSE,3.20 \r\nGayle,Davin,Tomas,Unt DP,MA,9,TRUE,3.60 \r\nKirk,Donovan,Baze,Unt DP,Phd,6,FALSE,3.50 \r\nSid,Carmen,Belair,Unt DP,MBA,18,TRUE,3.00 \r\nMiles,Conner,Mincey,Unt DP,MS,3,TRUE,3.80 \r\nAndreas,Jaylan,Chadburn,Unt DP,MA,21,TRUE,3.60 \r\nWilber,Tyree,Matthews,Unt DP,Phd,24,TRUE,3.30 \r\nGerardo,Cyrus,Mood,Unt DP,MBA,30,TRUE,3.50 \r\nElvis,Deja,Bigler,Unt DP,MS,18,TRUE,3.00 \r\nPercy,Karlee,Baumbach,Unt Main Campus,MA,3,TRUE,3.80 \r\nStevie,Raphael,Abdul,Unt Main Campus,Phd,21,TRUE,3.60 \r\nCraig,Riley,Magallanes,Unt Main Campus,MBA,18,TRUE,3.70 \r\nEvan,Trevor,Abe,Unt Main Campus,MS,9,FALSE,3.20 \r\nEmory,Kaila,Sockwell,Unt Main Campus,MA,6,FALSE,3.60 \r\nGeraldo,Gretchen,Rosel,Unt Main Campus,Phd,18,FALSE,3.50 \r\nCarter,Eduardo,Speight,Unt Main Campus,MBA,3,FALSE,3.40 \r\nKareem,Kamila,Kapoor,Unt Main Campus,MS,18,FALSE,3.40 \r\nCameron,Nikolas,Bernhard,Unt Main Campus,MBA,3,TRUE,3.00 \r\nJoseph,Gregory,Gross,Unt Main Campus,MS,21,TRUE,3.80 \r\nWilford,Leia,Harnish,Unt Main Campus,MA,24,TRUE,3.60 \r\nSeymour,August,Galaviz,Unt DP,Phd,30,FALSE,3.70 \r\nOmer,Cali,Poulos,Unt DP,MBA,18,FALSE,3.20 \r\nBobbie,Aarav,Cloninger,Unt DP,MS,3,FALSE,3.60 \r\nHorace,Scarlett,Mcglothlen,Unt DP,MA,21,TRUE,3.50 \r\nZachariah,Kenna,Mullins,Unt DP,Phd,24,FALSE,3.40 \r\nRhett,Victoria,Rosado,Unt DP,MBA,30,FALSE,3.40 \r\nRodolfo,Lorelai,Nimmo,Unt DP,MS,18,TRUE,3.50 \r\nArlie,Amya,Sundberg,Unt DP,MA,3,FALSE,3.00 \r\nRueben,Evan,Tillotson,Unt DP,Phd,21,TRUE,3.80 \r\nIra,Ethen,Lovell,Unt Main Campus,MBA,24,TRUE,3.60 \r\nAlonzo,Kameron,Rubi,Unt Main Campus,MBA,30,TRUE,3.30 \r\nBud,Brooklynn,Patrick,Unt Main Campus,MS,18,TRUE,3.50 \r\nBenton,Warren,Demars,Unt Main Campus,MA,3,FALSE,3.00 \r\nLarry,Fernando,Grothe,Unt DP,Phd,21,FALSE,3.80 \r\nMilford,Cory,Zambrano,Unt DP,MBA,24,TRUE,3.60 \r\nAdolfo,Jerry,Conlin,Unt DP,MS,18,TRUE,3.70 \r\nJohnathon,Elle,Giel,Unt Main Campus,MA,3,TRUE,3.20 \r\nGavin,Vicente,Collier,Unt Main Campus,Phd,21,TRUE,3.60 \r\nBuford,Layton,Primm,Unt Main Campus,MBA,18,FALSE,3.50 \r\nAlvin,Paris,Garmany,Unt DP,MS,9,FALSE,3.40 \r\nVal,Waylon,Tack,Unt Main Campus,MA,6,TRUE,3.40 \r\nJack,Ruth,Polzin,Unt Main Campus,Phd,18,FALSE,3.00 \r\nLanny,Rodney,Fout,Unt DP,MBA,3,FALSE,3.80 \r\nJody,Cedric,Plumadore,Unt DP,MS,18,FALSE,3.60 \r\nGaston,Maxim,Peabody,Unt DP,MA,3,TRUE,3.80 \r\nJosef,Helena,Hibbler,Unt Main Campus,Phd,21,FALSE,3.60 \r\nQuentin,Luciano,Archer,Unt Main Campus,MBA,18,FALSE,3.70 \r\nTod,Silas,Otis,Unt DP,MS,3,TRUE,3.20 \r\nBoyd,Wilson,Maday,Unt Main Campus,MBA,21,FALSE,3.60 \r\nTerri,Alonso,Boomhower,Unt Main Campus,MBA,24,TRUE,3.50 \r\nShondra,Jada,Sauls,Unt DP,MS,30,TRUE,3.40 \r\nKenyetta,Natalee,Pleasant,Unt Main Campus,MA,18,TRUE,3.40 \r\nClaudine,Aleah,Keatts,Unt Main Campus,Phd,3,TRUE,3.00 \r\nJanel,Nathanael,Cutright,Unt Main Campus,MBA,21,FALSE,3.80 \r\nMaisie,Mason,Claflin,Unt DP,MS,18,FALSE,3.60 \r\nMichelle,Jasper,Kamin,Unt Main Campus,MA,9,TRUE,3.70 \r\nDrucilla,Rafael,Oshiro,Unt DP,Phd,6,FALSE,3.20 \r\nWilhemina,Kolton,Dear,Unt DP,MBA,18,FALSE,3.60 \r\nCaitlyn,Alvin,Weisenberger,Unt DP,MS,3,TRUE,3.50 \r\nDomitila,Kaydence,Winans,Unt Main Campus,MA,18,FALSE,3.40 \r\nJenice,Estrella,Canizales,Unt Main Campus,MBA,3,FALSE,3.40 \r\nVerena,Naima,Lamica,Unt DP,MS,21,FALSE,3.80 \r\nDwana,Hope,Odell,Unt Main Campus,MA,24,TRUE,3.60 \r\nLesli,Abraham,Brazel,Unt Main Campus,Phd,30,FALSE,3.70 \r\nSilvia,Alexus,Quackenbush,Unt DP,MBA,18,FALSE,3.20 \r\nConchita,Lana,Sauders,Unt Main Campus,MS,3,TRUE,3.60 \r\nSherryl,Emily,Forry,Unt Main Campus,MA,21,FALSE,3.50 \r\nDulce,Sydney,Zukowski,Unt DP,Phd,24,TRUE,3.40 \r\nAsia,Reese,Yohe,Unt DP,MBA,30,TRUE,3.40 \r\nLuetta,Alessandra,Spence,Unt DP,MS,18,FALSE,3.40 \r\nJulissa,Chandler,Walch,Unt Main Campus,MBA,3,TRUE,3.50 \r\nSabina,Rolando,Prager,Unt Main Campus,MS,21,TRUE,3.00 \r\nMonique,Cloe,Danforth,Unt DP,MS,24,TRUE,3.80 \r\nAlane,Armando,Parikh,Unt Main Campus,MS,30,FALSE,3.60 \r\nFerne,Amari,Tolliver,Unt Main Campus,MS,18,FALSE,3.30 \r\nRossie,Bailey,Danley,Unt DP,MS,3,FALSE,3.50 \r\nStarla,Vincent,Poche,Unt Main Campus,MS,21,TRUE,3.00 \r\nBethann,Keon,Metcalf,Unt Main Campus,MS,24,FALSE,3.80 \r\nBarbara,Eduardo,Goebel,Unt DP,MS,18,FALSE,3.60 \r\nCamilla,Kolby,Sandiford,Unt DP,MS,3,TRUE,3.70 \r\nStephanie,Odin,Fludd,Unt DP,MS,21,FALSE,3.20 \r\nLovetta,Phoebe,Irons,Unt Main Campus,MS,18,TRUE,3.60 \r\nJoana,Ignacio,Sindelar,Unt Main Campus,MS,24,TRUE,3.50 \r\nEdra,Noemi,Guerrant,Unt DP,MS,30,TRUE,3.40 \r\nJennifer,Gauge,Czerwinski,Unt Main Campus,MS,18,FALSE,3.40 \r\nIlona,Theodore,Vangieson,Unt Main Campus,MS,3,FALSE,3.00 \r\nBritni,Siena,Alvord,Unt DP,MS,21,TRUE,3.80 \r\nLenora,Quintin,Arambula,Unt Main Campus,MS,24,FALSE,3.60 \r\nDebi,Keyla,Weigand,Unt Main Campus,MS,30,TRUE,3.80 \r\nErika,Raymond,Daum,Unt DP,MA,18,TRUE,3.40 \r\nDonetta,Judith,Fukuda,Unt DP,Phd,3,TRUE,3.40 \r\nPhyliss,Angelique,Shawl,Unt DP,MBA,21,FALSE,3.00 \r\nAlix,Peyton,Wren,Unt Main Campus,MS,24,FALSE,3.80 \r\nJung,Matias,Speece,Unt Main Campus,MBA,18,TRUE,3.60 \r\nSalome,Vincent,Casiano,Unt DP,MS,3,FALSE,3.80 \r\nIliana,Roderick,Bourke,Unt Main Campus,MS,21,TRUE,3.00 \r\nRafaela,Riya,Welden,Unt Main Campus,MS,18,TRUE,3.80 \r\nNan,Lucia,Dinkins,Unt DP,MS,3,TRUE,3.60 \r\nTheresa,Sloane,Throckmorton,Unt Main Campus,MS,21,TRUE,3.80 \r\n'}

In [13]:
df = pd.read_csv('assignment1Sort.csv')
df.sort_values('Last Name')

   First Name Middle Initial  ... Scholarship Received  GPA
11     Stevie        Raphael  ...                 True  3.6
13       Evan         Trevor  ...                False  3.2
87     Britni          Siena  ...                 True  3.8
88     Lenora        Quintin  ...                False  3.6
47    Quentin        Luciano  ...                False  3.7
10      Percy         Karlee  ...                 True  3.8
3        Kirk        Donovan  ...                False  3.5
4         Sid         Carmen  ...                 True  3.0
18    Cameron        Nikolas  ...                 True  3.0
9       Elvis           Deja  ...                 True  3.0
50      Terri         Alonso  ...                 True  3.5
96     Iliana       Roderick  ...                 True  3.0
64      Lesli        Abraham  ...                False  3.7
61     Jenice       Estrella  ...                False  3.4
95     Salome        Vincent  ...                False  3.8
6     Andreas         Jaylan  ...                 True  3.6
55     Maisie          Mason  ...                False  3.6
23     Bobbie          Aarav  ...                False  3.6
38      Gavin        Vicente  ...                 True  3.6
36     Adolfo          Jerry  ...                 True  3.7
54      Janel      Nathanael  ...                False  3.8
85   Jennifer          Gauge  ...                False  3.4
73    Monique           Cloe  ...                 True  3.8
76     Rossie         Bailey  ...                False  3.5
90      Erika        Raymond  ...                 True  3.4
58  Wilhemina         Kolton  ...                False  3.6
33     Benton         Warren  ...                False  3.0
98        Nan          Lucia  ...                 True  3.6
81  Stephanie           Odin  ...                False  3.2
67    Sherryl          Emily  ...                False  3.5
..        ...            ...  ...                  ...  ...
39     Buford         Layton  ...                False  3.5
65     Silvia         Alexus  ...                False  3.2
26      Rhett       Victoria  ...                False  3.4
15    Geraldo       Gretchen  ...                False  3.5
31     Alonzo        Kameron  ...                 True  3.3
80    Camilla          Kolby  ...                 True  3.7
66   Conchita           Lana  ...                 True  3.6
51    Shondra           Jada  ...                 True  3.4
92    Phyliss      Angelique  ...                False  3.0
83      Joana        Ignacio  ...                 True  3.5
14      Emory          Kaila  ...                False  3.6
94       Jung         Matias  ...                 True  3.6
16     Carter        Eduardo  ...                False  3.4
70     Luetta     Alessandra  ...                False  3.4
28      Arlie           Amya  ...                False  3.0
41        Val         Waylon  ...                 True  3.4
99    Theresa         Sloane  ...                 True  3.8
29     Rueben           Evan  ...                 True  3.8
75      Ferne          Amari  ...                False  3.3
2       Gayle          Davin  ...                 True  3.6
86      Ilona       Theodore  ...                False  3.0
71    Julissa       Chandler  ...                 True  3.5
89       Debi          Keyla  ...                 True  3.8
59    Caitlyn          Alvin  ...                 True  3.5
97    Rafaela           Riya  ...                 True  3.8
60   Domitila       Kaydence  ...                False  3.4
93       Alix         Peyton  ...                False  3.8
69       Asia          Reese  ...                 True  3.4
35    Milford           Cory  ...                 True  3.6
68      Dulce         Sydney  ...                 True  3.4

[100 rows x 8 columns]